# Cloud Build config for LibreChat: build → push → deploy to Cloud Run
# Matches exact pattern of working MCP toolbox config

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mcp-librechat/librechat-api:${BRANCH_NAME}-latest'
      - '.'

  # Step 2: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mcp-librechat/librechat-api:${BRANCH_NAME}-latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e

        if [ "${BRANCH_NAME}" = "dev" ]; then
          SERVICE_NAME="librechat-dev"
          SECRET_YAML="librechat-dev-yaml"
          SECRET_ENV="librechat-dev-env"
        elif [ "${BRANCH_NAME}" = "stage" ]; then
          SERVICE_NAME="librechat-stage"
          SECRET_YAML="librechat-stage-yaml"
          SECRET_ENV="librechat-stage-env"
        elif [ "${BRANCH_NAME}" = "master" ] || [ "${BRANCH_NAME}" = "main" ]; then
          SERVICE_NAME="librechat-live"
          SECRET_YAML="mpc-librechat-yaml-live"
          SECRET_ENV="mpc-librechat-env-live"
        else
          echo "ERROR: Unsupported branch ${BRANCH_NAME}"
          exit 1
        fi

        echo "Deploying to Cloud Run service: $$SERVICE_NAME"
        echo "Using secrets: YAML=$SECRET_YAML, ENV=$SECRET_ENV"

         gcloud run deploy "$$SERVICE_NAME" \
          --image "us-central1-docker.pkg.dev/$PROJECT_ID/mcp-librechat/librechat-api:${BRANCH_NAME}-latest" \
          --region "us-central1" \
          --platform "managed" \
          --allow-unauthenticated \
          --service-account "toolbox-identity@$PROJECT_ID.iam.gserviceaccount.com" \
          --set-secrets "/app/librechat.yaml=$SECRET_YAML:latest,/app/.env=$SECRET_ENV:latest" \
          --timeout "1200s" \
          --labels "branch=${BRANCH_NAME},commit=${SHORT_SHA}" \
          --cpu=1 \
          --memory=1Gi \
          --port=3080 [web:10]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/mcp-librechat/librechat-api:${BRANCH_NAME}-latest'
