# Cloud Build config for LibreChat: build → push → deploy to Cloud Run
# Uses Artifact Registry, Secret Manager, and mounts secrets as files in the container.

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  # Provide defaults; override in trigger
  _REGION: us-central1
  _REPOSITORY: mcp-librechat
  _IMAGE_NAME: librechat-api
  _SERVICE_DEV: librechat-dev
  _SERVICE_STAGE: librechat-stage
  _SERVICE_PROD: librechat-live
  # Separate secrets for file mounts; always use latest version
  _SECRET_DEV_YAML: librechat-dev-yaml
  _SECRET_DEV_ENV: librechat-dev-env
  _SECRET_STAGE_YAML: librechat-stage-yaml
  _SECRET_STAGE_ENV: librechat-stage-env
  _SECRET_PROD_YAML: mpc-librechat-yaml-live
  _SECRET_PROD_ENV: mpc-librechat-env-live

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${BRANCH_NAME}-latest'
      - '.'

  # Step 2: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${BRANCH_NAME}-latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        
        # Select service and secrets by branch using substitutions
        if [ "${BRANCH_NAME}" = "dev" ]; then
          SERVICE_NAME="${_SERVICE_DEV}"
          SECRET_YAML="${_SECRET_DEV_YAML}"
          SECRET_ENV="${_SECRET_DEV_ENV}"
        elif [ "${BRANCH_NAME}" = "stage" ]; then
          SERVICE_NAME="${_SERVICE_STAGE}"
          SECRET_YAML="${_SECRET_STAGE_YAML}"
          SECRET_ENV="${_SECRET_STAGE_ENV}"
        elif [ "${BRANCH_NAME}" = "master" ] || [ "${BRANCH_NAME}" = "main" ]; then
          SERVICE_NAME="${_SERVICE_PROD}"
          SECRET_YAML="${_SECRET_PROD_YAML}"
          SECRET_ENV="${_SECRET_PROD_ENV}"
        else
          echo "ERROR: Unsupported branch ${BRANCH_NAME}"
          exit 1
        fi

        echo "Deploying to Cloud Run: ${SERVICE_NAME}"
        echo "Using Secret Manager secrets: YAML=${SECRET_YAML}, ENV=${SECRET_ENV}"

        # Deploy with both secrets mounted as files (single-line --set-secrets)
        gcloud run deploy "${SERVICE_NAME}" \
          --image "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${BRANCH_NAME}-latest" \
          --region "${_REGION}" \
          --platform "managed" \
          --allow-unauthenticated \
          --timeout "1200s" \
          --labels "branch=${BRANCH_NAME},commit=${SHORT_SHA}" \
          --service-account "toolbox-identity@$PROJECT_ID.iam.gserviceaccount.com" \
          --cpu=1 \
          --memory=1Gi \
          --port=3080 \
          --set-secrets "/app/librechat.yaml=${SECRET_YAML}:latest,/app/.env=${SECRET_ENV}:latest" [web:10][web:14]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${BRANCH_NAME}-latest'
